# Generated by Django 3.1.7 on 2021-03-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0003_auto_20210309_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
