# Generated by Django 3.1.7 on 2021-03-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0004_auto_20210309_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=15)),
                ('idea_content', models.TextField()),
            ],
        ),
    ]
