# Generated by Django 3.1.7 on 2021-03-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0006_queryform'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('place', models.CharField(help_text='Ex: Jaipur, Rajasthan', max_length=150)),
                ('skills', models.CharField(help_text='Enter skills comma(,) separated', max_length=500)),
            ],
        ),
    ]
